"""comments

Revision ID: 782d11dade61
Revises: b07eaf610560
Create Date: 2022-02-16 06:12:15.565584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '782d11dade61'
down_revision = 'b07eaf610560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('comment', 'posted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'posted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comment', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
